### ISSUE TITLE
Communicate that the ‘required’ email address field is not actually required by the Archive but by Omeka

### ISSUE THREAD

**Issue by helrond** [helrond/plugin-Contribution#3]
It would be ideal if this could be removed, but given that this is unlikely, @jmdrake1959 created a workaround whereby users are given an explanation via a text box that describes why they may or may not choose to provide an email address. 

>This field will not be displayed to the public. If you do not have an email address or prefer not to share it, use papvcleveland@gmail.com. Providing your email address will allow us to contact you with any questions about your contribution. However, please know that providing your email address may also allow authorities to determine your identity with a subpoena or court order. We also cannot provide any protection against retaliation by police or other law enforcement officials for telling these stories, so please protect your identity if possible. Whichever email address you enter into this field, enter it into the required email field below.

**Comment by ruthtillman** [comment]
I think it may be possible to dig into the code and write something that automatically passes papvcleveland@gmail.com through to the form if someone doesn't add their own email address. I can look into that. If that works, then we can just put "Not required" and part of @jmdrake1959's disclaimer about what happens if they provide it. The above seems like the easiest solution, but mine would require one fewer step from the users so I'd like to see if we can do it. I'll look at that this weekend.

**Comment by helrond** [comment]
I don't know for sure, but I wonder if one of the potential implications here is that contributors lose the ability to edit/delete their contributions if their account isn't tied to an email address.

Additionally, things like password reset are sent via the email associated with an account, so there's the real possibility that someone could lose ownership of their account entirely.

**Comment by helrond** [comment]
Would also be worth checking to see if email addresses need to be unique within an Omeka instance.

**Comment by helrond** [comment]
Contribution plugin documentation is [thisaway](http://omeka.org/codex/Plugins/Contribution_2.0)

**Comment by ruthtillman** [comment]
>Would also be worth checking to see if email addresses need to be unique within an Omeka instance.
4 tests on local instance:
1. Submitted with new email. Asked to be anonymous. Submission goes through and guest user is created. Came with note that it was anonymous but logged record oc email in Omeka back-end.
2. Submitted second item under same email as 1. Didn't ask to be anonymous. Went through fine again. No note about anonymity. Assigned to same guest user.
3. Submitted third item using SuperUser's email. Asked to be anonymous. Submission goes through including (Anonymous) but assigned to SuperUser.
4. Same but not-anonymous. Also assigned to SuperUser with no anonymous flag.

Neither the anonymity of the submission nor to whom it was assigned actually mattered in the public display of the website once it was approved, however. None had any kind of publicly visible user information.

**Comment by ruthtillman** [comment]
Working with Jarrett, determined separate form field sufficient for catching email with appropriate warning comments. Set field to use papvcleveland@gmail.com unless user was logged in and then set overall form of field to display:none with very basic inline html styling. Not reinventing the dead horse. Changed in commit 1 on branch ruth.
